# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Hitomi Tee - Homepage"
#description              : "Master's Student at SJTU"
repository               : "hitomitee/hitomitee.github.io"
google_scholar_stats_use_cdn : false

# google analytics
google_analytics_id      : 

# SEO Related
google_site_verification : 

# Site Author
author:
  name             : "Hitomi Tee Jin Ling"
  avatar           : "images/avatar2.jpg"
  bio              : "Carpe Diem"
  location         : "Shanghai, China"
  university       : "SJTU"
  pubmed           : 
  googlescholar    : 
  email            : "hitomiteejinling@link.cuhk.edu.cn"
  cv               :  #"/assets/pdf/CV_HTJL.pdf"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "hitomitee"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         :
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shenzhen # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
